name: Java Package

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-java@v3
          with:
            distribution: 'zulu' # See 'Supported distributions' for available options
            java-version: '17'
        - run: chmod +x ./buildMe.sh
        - run: ./buildMe.sh
