name: Java Package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:

    steps:
	- uses: actions/checkout@v3
	- uses: actions/setup-java@v3
	  with:
	    distribution: 'zulu' # See 'Supported distributions' for available options
	    java-version: '17'
	- run: cd src
	- run: javac HelloWorldApp.java